Import("env")

from pathlib import Path
import json
import os
import subprocess

project_dir = Path(env.subst("$PROJECT_DIR"))
pioenv = env.subst("$PIOENV")
build_root = Path(env.subst("$BUILD_DIR"))
generated_dir = build_root / pioenv / "generated"
generated_dir.mkdir(parents=True, exist_ok=True)


def sanitize_sha(value):
    value = (value or "").strip()
    value = "".join(c for c in value if c.isalnum() or c in "._-")
    return value[:8]


def github_source_sha():
    """Return the real source commit for GitHub Actions builds.

    pull_request workflows are checked out at GitHub's synthetic merge commit.
    Read the event payload first so the firmware records the PR head commit
    instead of that temporary merge SHA. Push/workflow_dispatch builds can use
    GITHUB_SHA directly.
    """
    if os.environ.get("GITHUB_ACTIONS", "").lower() != "true":
        return ""

    event_path = os.environ.get("GITHUB_EVENT_PATH", "")
    if event_path:
        try:
            payload = json.loads(Path(event_path).read_text(encoding="utf-8"))
            pr_sha = (
                payload.get("pull_request", {})
                .get("head", {})
                .get("sha", "")
            )
            pr_sha = sanitize_sha(pr_sha)
            if pr_sha:
                return pr_sha
        except Exception:
            pass

    return sanitize_sha(os.environ.get("GITHUB_SHA", ""))


def local_git_sha():
    try:
        value = subprocess.check_output(
            ["git", "rev-parse", "--short=8", "HEAD"],
            cwd=str(project_dir),
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
        return sanitize_sha(value)
    except Exception:
        return ""


def git_sha():
    return github_source_sha() or local_git_sha() or "source-archive"


sha = git_sha()
header_path = generated_dir / "git_version_generated.h"
header_content = (
    "#pragma once\n"
    "// Auto-generated by scripts/git_version.py. Do not edit.\n"
    "#ifdef GIT_COMMIT_HASH\n"
    "#undef GIT_COMMIT_HASH\n"
    "#endif\n"
    f'#define GIT_COMMIT_HASH "{sha}"\n'
)

# Avoid touching the generated file if its contents did not change.
if not header_path.exists() or header_path.read_text(encoding="utf-8") != header_content:
    header_path.write_text(header_content, encoding="utf-8")

env.Append(CPPPATH=[str(generated_dir)])
print("Firmware Git commit:", sha)
