Import("env")

from pathlib import Path
import subprocess

project_dir = Path(env.subst("$PROJECT_DIR"))
pioenv = env.subst("$PIOENV")
build_root = Path(env.subst("$BUILD_DIR"))
generated_dir = build_root / pioenv / "generated"
generated_dir.mkdir(parents=True, exist_ok=True)


def git_sha():
    try:
        value = subprocess.check_output(
            ["git", "rev-parse", "--short=8", "HEAD"],
            cwd=str(project_dir),
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
        # Keep only characters that are safe inside a generated C string.
        value = "".join(c for c in value if c.isalnum() or c in "._-" )
        return value[:32] or "source-archive"
    except Exception:
        return "source-archive"


sha = git_sha()
header_path = generated_dir / "git_version_generated.h"
header_content = (
    "#pragma once\n"
    "// Auto-generated by scripts/git_version.py. Do not edit.\n"
    f'#define GIT_COMMIT_HASH "{sha}"\n'
)

# Avoid touching the generated file if its contents did not change.
if not header_path.exists() or header_path.read_text(encoding="utf-8") != header_content:
    header_path.write_text(header_content, encoding="utf-8")

env.Append(CPPPATH=[str(generated_dir)])
print("Firmware Git commit:", sha)
